on:
  workflow_dispatch:
name: test
permissions:
  id-token: write
  contents: read
  
jobs:
  my_job:
    name: login to azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.TENANT_ID }}
        environment: test
    - name: list az accounts
      uses: Azure/cli@v1.0.8
      with:
        inlineScript: az account --list
        
  
    
 
