on:
  workflow_dispatch:
name: test
permissions:
  id-token: write
  contents: read
  
jobs:
  my_job:
    name: login to azure
    runs-on: ubuntu-latest
    steps:
    - name: Install azure-cli
      uses: pietrobolcato/install-azure-cli-action@v1.0.1
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.TENANT_ID }}
        environment: test
      
  
    
 
